crashappsec/chalk

.github/copyright.tmpl
LICENSE
Makefile
chalk.nimble
docker-compose.yml
src/configs/README.md
tests/test_command.py

after the initial OSS release, a few nuances were missed which this pr fixes:
* removes hard dependency on `.github/Makefile.dist` in `Makefile`
* removes internal license from `LICENSE`
* adds `nimble release` task to `chalk.nimble`
* adds necessary docker-compose services to run tests
* fixes version check test to support `chalk.nimble`
* sync in md files
* adds the copyright check pre-commit template file so pre-commit works

misc fixes for the OSS repo

---

.github/workflows/lint.yml
.github/workflows/tests.yml
.gitignore
LICENSE
Makefile
docker-bake.hcl

this adds automatic github actions for running linting/test checks on open PRs.
linting checks are validated by https://pre-commit.com/
other tests are using https://github.com/pytest-dev/pytest
---
tests only run when there are any source code changes (e.g. changes to `.nim` files). to test PR tests I temporarily enabled running them even without any source code changes (as this PR doesnt change any source files). that test run can be seen on:
https://github.com/crashappsec/chalk/actions/runs/6342089679/job/17227124600?pr=8
tests pass 🎉

adding github actions for lint/tests

---

.github/workflows/tests.yml
README.md

This change adds a badge (svg image) to the repo README which shows the status of the tests CI pipeline.
Hopefully it will show just that tests are passing all the time :wink:
The badge also links to the github action page which shows the history of the tests running on main branch. Speaking of the main branch, the badge only shows
tests status for the main branch so that if any tests fail on any PRs, they will not impact the badge status.
Finally this change only runs tests on merges to main only when any of the source code changes so that we dont run tests for things like documentation changes.

adding tests badge to the repository README

---

chalk.nimble
src/chalk_common.nim
src/collect.nim
src/commands/cmd_docker.nim
src/configs/chalk.c42spec
src/docker_base.nim
src/docker_cmdline.nim
src/plugins/codecDocker.nim
src/util.nim

Generally, systems use /tmp for temporary files, and most modern API interfaces to using /tmp take mitigation against file-based race conditions, for instance, by leveraging per-app directories and randomness in selecting file names.
However, there are times when the system default isn't a good option for Chalk when it needs temporary space. Specifically, we've learned that, for those running Docker via Snap on Ubuntu systems, Snap's isolation of temporary files means that users will get an error if we try to use /tmp to, for instance, write out a temporary docker file that we want to use with a container.
To mitigate that problem, the primary use of tmp directories in the docker path is for writing out a temporary docker file whenever additions are requested. With this PR, when we need …

Minimize use of tmpfiles when storing Dockerfiles

---

src/chalk.nim
src/commands/cmd_help.nim

I am now special casing when the --help flag is passed, so that it never gets passed as a search argument to the 'help' command; it always triggers command help.
I also tweaked the behavior of how the flag works in the presence of a default command-- it now gives the global help if the command was NOT explicitly provided, instead of the help for the implicit command-- this seems like much more expected behavior for novices.
Closes #11

[enhancement] Make --help behavior more intuitive

---

.dockerignore
.gitignore
Makefile
docker-compose.yml
tests/Dockerfile
tests/chalk/runner.py
tests/conf.py
tests/conftest.py
tests/gdb/__init__.py
tests/gdb/callback.py
tests/gdb/commands.gdb
tests/pytest.ini
tests/test_config.py
tests/test_elf.py
tests/test_exec.py
tests/utils/dict.py
tests/utils/os.py

@indecisivedragon  did most of the work for the gdb stuff so she deserves the credit! (Im just syncing between repos here for the most part)
gdb tests check some basic things about elf encoding by:
* running binary before chalking it and reporting:
* couple of dozen bytes after the program entrypoint as seen in the gdb breakpoint
* chalking the binary
* running same gdb script on the chalked binary and comparing the report before chalk and after. If all goes well, there should not be any difference in the instructions of the entrypoint comparing chalked and non-chalked binary.
In the future we can add more checks here as whatever json gdb script outputs to stdout test will automatically compare.
Speaking of json, some of the bits for looking for valid json in the os.py/runner.py needed to …

test(gdb): adding gdb tests for elf encoding (on behalf of Liming)

---

src/docker_base.nim

Currently `docker_exe` was being appended to PATH which meant that given `docker_exe` configuration didnt take any precedence in case there are multiple `docker` instances on `PATH` (which seems to be case, at least in Ubuntu).
By prepending provided path, if exists, takes precedence over other dirs in PATH.

fix(docker): prepending docker_exe to PATH

---

.github/check_version.sh
.pre-commit-config.yaml

this will check chalk version matches across various files. currently we only check:
* nimble file
* base_keyspecs.c4m
If the chalk version is updated in nimble file, all other files need to match it.
Adds automatic check for ensuring all version numbers match
Follow up to https://github.com/crashappsec/chalk/pull/29
```
pre-commit run --all-files
```

test(lint): adding pre-commit hook for checking chalk version across files

---

src/commands/cmd_docker.nim
src/docs/core-release-notes.md
tests/chalk/runner.py
tests/data/configs/docker_heartbeat.conf
tests/data/dockerfiles/valid/sleep/Dockerfile
tests/data/dockerfiles/valid/sleep/sleep.sh
tests/test_docker.py
tests/utils/docker.py
tests/utils/os.py

heartbeat test is flaky
The root cause was that probe build to get current build platform, docker tag name was random which sometimes resulted in invalid tag names:
```
ERROR: invalid tag ".mpiljfkim.ahsfgpf3f4g": invalid reference format
```
docker tag names need to start/end with alphanumeric character so to solve it adding `chalk_` and `_probe` prefix/suffix. This ensures the build tag is correct and docker can build it.
```sh
until not 'make tests args="test_docker.py::test_docker_heartbeat --slow --pdb"'
```

fix(heartbeat): fixing flaky heartbeat test due to invalid probe build tag

---

docker-bake.hcl
tests/README.md

closes #https://github.com/crashappsec/chalk-internal/issues/835
This updates the README.md in tests to be more informative and useful.

docs: improve developer doc for testing

---

tests/chalk/runner.py
tests/data/dockerfiles/valid/sleep/sleep.sh
tests/test_docker.py

Fixing heartbeat test which is failing on `main`
it excludes all log lines so that it can extract only json reports without any json blobs which might of been logged in regular log messages
```sh
➜ make tests args="test_docker.py::test_docker_heartbeat --slow --logs --pdb"
```
tests:--slow

test(heartbeat): fixing reports utility matching logs

---

tests/data/configs/composable/valid/valid_1.c4m
tests/test_composable.py

followup on https://github.com/crashappsec/chalk-internal/issues/851
This pr enables some tests that were disabled due to chalk bugs

fix: minor testing fixes for composable config testing

---

configs/reporting_server.c4m
tests/data/configs/composable/valid/compliance_docker/reporting_server.c4m

related to https://github.com/crashappsec/chalk/issues/75 -- fixes the config so that we can be sure which part is failing
reporting server output sink was not actually subscribed to
see ticket

fix: reporting server config fix

---

configs/reporting_server.c4m
tests/data/configs/composable/valid/compliance_docker/reporting_server.c4m

related to https://github.com/crashappsec/chalk/issues/75
default url needs to end in `/report` to hit the correct endpoint in the api server

fix: chalk should push reports to report endpoint

---

src/configs/sbomconfig.c4m

When syft has one component (as opposed to 0 or 2), it changes the key name to "component", which was bungling detection.
It's 'validity' check just now looks for: "component
Not the whole key.

Fix syft with a single component

---

README.md

Removes how-to links to missing pages that are 404ing

fix: remove broken links to removed how-tos

---

tests/data/configs/composable/valid/sboms/enable_sboms.c4m
tests/test_plugins.py

testing update for https://github.com/crashappsec/chalk/issues/82
adds tests to check that sboms have been embedded into docker + binaries if `embed_sboms` is enabled

test: ensure sboms tools actually run and embed

---

chalk.nimble

Closes #63 
Nothing is  this PR is directly implemented in Chalk; the implementation was in Nimutils, and this picks up the nimutils version via picking up the newest Con4m.
There's now one incredibly flexible subprocess API, with both a one-shot interface and a builder-style interface. It can do PTYs, capture, callbacks, socket listeners, etc.
The existing subprocess stuff has been all re-written on top of it (we didn't use Nim's built-in stuff because it didn't provide even basic niceties we needed, like being able to capture all of, stdin, stdout and the return code for one process). And it certainly didn't have pty support.
The old API remained for compatibility with chalk though.
The reason for this refactor wasn't the existing subprocess support, it was for future capabilities:
1. …

refactor: subprocess IO

---

chalk.nimble
config.nims

The fact that the C and Nim APIs disagreed on sign for an integer led to process output capture not getting presented... but only in very rare (but reproducible cases). I haven't even figured out why this mattered or why it didn't work yet. But this seems to fix it?
Pull in a new nimutils that just changes a 'cint' to a 'csize_t'.  Seriously.
If all tests pass, the broken case we found seems to be working on multiple boxes.

fix: capture heisenbug

---

tests/chalk/runner.py
tests/test_plugins.py
tests/utils/os.py

as tests touch common vendor file, they cannot run in parallel and need to be marked as exclusive. the fact that it passes in CI is probably just an indicator that it has much fewer cores and they dont overlap with each other but otherwise they are found to fail
also ignoring docker debug error logs from docker build helper
tests are failing on main
```
make tests_parallel args="test_plugin.py"
```

tests: fixing exclusive plugin tests

---

src/selfextract.nim

When chalk binary has only execute permission:
```
$ ls -la chalk
-rwx--x--x  1  root  sudo  10114504 Dec  5 00:27 chalk
```
Chalk binary can execute however during self-extract it will be unable to read itself therefore would be unable to load embedded config and chalk proceeds running with default configs which is incorrect. This adds a check during self-extract which ensures chalk has read permission on itself.
found this issue while using github action

fix: checking chalk permissions on self-extract

---

src/commands/cmd_docker.nim
tests/chalk/runner.py
tests/test_docker.py
tests/utils/docker.py

```
chalk docker build -t foo -t bar --push .
```
this would only push `foo` tag and not push `bar` tag
When specifying multiple tags during `docker build`, all tags are pushed to the registry when `--push` flag is used.
```
➜ make tests args="test_docker.py::test_multiple_tags --logs"
```

fix: pushing all docker tags on build --push

---

chalk.nimble
src/chalk_common.nim
src/configs/base_auths.c4m
src/configs/base_keyspecs.c4m
src/configs/base_sinks.c4m
src/configs/chalk.c42spec
src/sinks.nim
tests/data/sink_configs/post_http_local.c4m
tests/data/sink_configs/post_https_local.c4m

This will allow to easily add reusable auth configurations to sinks:
```
auth_config myauth {
auth:     "basic"
username: env("USERNAME")
password: env("PASSWORD")
}
sink_config mysink {
sink: "post"
uri:  "http://example.com/report"
auth: "myauth"
}
```
```
make tests args="test_sink.py"
```

feat(auth): adding basic/jwt auth configurations

---

src/configs/base_report_templates.c4m

Fixes #115
This PR adds `_ACTION_ID` to the default `push` template
Issue a `push` command and see that `_ACTION_ID` is properly set

fix: added _ACTION_ID in push template and moved to the top of all report template configs

---

.pre-commit-config.yaml
src/commands/cmd_docker.nim
src/util.nim
tests/data/dockerfiles/valid/cmd/json.Dockerfile
tests/data/dockerfiles/valid/cmd/string.Dockerfile
tests/test_docker.py

`CMD` wrapping breaks shell commands such as `set -x && echo hello`
in that case `chalk` will attempt to exec `set` which will fail as its not an executable and will throw:
```
No executable named 'set' found in your path
```
`CMD` when being a string can be a shell script which directly wrapping `CMD` directive breaks. By wrapping it with `ENTRYPOINT` it allows to honor any shell scripts
Only edge case is if base image has any custom `ENTRYPOINT`, that `ENTRYPOINT` will break as it will be overwritten. Proper fix will be coming in next release
```
➜ make tests args="test_docker.py::test_cmd_wrap --logs"
```

fix: supporting shell commands in CMD wrapping

---

tests/chalk/runner.py
tests/test_plugins.py
tests/utils/dict.py

tests on main are failing as new version of semgrep was released
https://github.com/semgrep/semgrep/releases/tag/v1.57.0
otherwise semgrep tests are very fragile
in order to facilitate that, improving dict comparison util by adding SubsetCompare which correctly handles nested lists which previously was not possible to handle gracefully in as CompareMixin is a dict child
```
➜ make tests args="test_plugins.py::test_semgrep[sample_1] --pdb"
```

tests: not asserting full semgrep test output

---

chalk.nimble
src/plugins/codecElf.nim

Due to the addition of new dependencies that weren't build for arm, the Chalk build on ARM wasn't working.
Updated downstream dependencies.

Updated ARM64 support

---

src/configs/chalk.c42spec
src/configs/getopts.c4m
tests/chalk/runner.py
tests/test_command.py

No issue
Remove the `--no-api-login` switch as it longer has relevance since the `chalk setup` flow changed and no longer requires an interactive OIDC authentication. 
Tests that included the switch have also been refactored.

refactor(no-api-login)!: remove the --no-api-login switch + assoc. tests

---

src/docs/core-release-notes.md

None.
Update the release notes for chalk 0.3.1.
None.

docs(core-release-notes): update for chalk 0.3.1

---

chalk.nimble
docker-compose.yml
tests/data/sink_configs/s3.c4m

Previously if `region` config value was omitted, region was defaulted to `us-east-1` even if either `AWS_DEFAULT_REGION` or `AWS_REGION` were present. This is fixed now in nimutils

fix: honoring AWS region env vars for s3 sink config

---

src/configs/ioconfig.c4m

running `chalk extract` in github does not show any report back:
this will show the report using github sink filter for `extract` and `push`, same as we do for `build` and `insert`

fix: showing chalk docker report in github on extract

---

src/selfextract.nim
tests/chalk/runner.py
tests/test_config.py

https://github.com/crashappsec/chalk/issues/74
When adding line to the config for the component, checks if that line is already present. This avoid adding duplicate lines to the config
```
➜ make tests args="test_config.py::test_load_duplicate --logs --pdb"
```

fix: not loading same component multiple times

---

configs/connect.c4m
src/attestation.nim
src/commands/cmd_setup.nim
src/configs/chalk.c42spec
tests/test_command.py

When `chalk.pub`/`chalk.key` and `CHALK_PASSWORD` is already provided, chalk would not save them into chalkmark. Chalkmark was only updated when new key material was being generated. As such it was not possible to reuse existing keys aside from sharing binary itself.
```
➜ make tests args="test_command.py::test_setup_existing_keys --logs --pdb"
```

fix: chalk setup does not save existing keys

---

src/attestation.nim

https://github.com/crashappsec/chalk/issues/186
not in all cases service returns valid json for non-200 responses and so we should not parse it assuming it has valid json which caused segfault
point signing service to dummy endpoint which doesnt return json back

fix: handling non-json responses from signing backup service

---

CHANGELOG.md
src/attestation.nim
src/commands/cmd_setup.nim

cosign service wasnt handling cases when cosign service was not
accessible at all as `safeRequest` was throwing unhandled exception
https://github.com/crashappsec/chalk/issues/186
cosign has 3 pieces of information:
* public key
* encrypted private key
* password to decrypt private key
When loading cosign, all 3 pieces are required. However when validating
already signed signature only public key is required. Currently cosign
setup was always fetching password to decrypt private key. Changed that
to only fetch password for insert/build/push operations as they are the
only operations which can generate a signature.
```
➜ cat dummy.c4m
log_level: "trace"
use_signing_key_backup_service = true
signing_key_backup_service_url = "http://localhost:8000"
docker.wrap_entrypoint = true
auth_config …
```

fix(cosign): not acquiring password for signature validation

---

chalk.nimble
src/config_version.nim
src/configs/base_keyspecs.c4m
src/semver.nim

dev builds when chalk is not on a release results in showing version as if its for a release
this will allow to bump version to `*-dev` immediately after the release to denote chalk is for a dev version
this is especially useful for publishing chalk to other platforms such as to docker hub/etc
as nimble does not support suffixes, its ignored there:
```
➜ nimble version | tail -n1
0.3.3
➜ make version
0.3.3-dev
➜ ./chalk version 2> /dev/null | grep -i version
┊ Chalk Version  ┊ 0.3.3-dev                                   ┊
```

build: adding -dev support to chalk version

---

src/semver.nim

Follow up for https://github.com/crashappsec/chalk/pull/195#discussion_r1483527333 - my review was one minute too slow.
The intention is to use the last ASCII code point (127 in decimal), to implement basic version precedence.
From the [Nim manual on string literals][manual]:
`\x` HH      character with hex value HH; exactly two hex digits are allowed
`\u` HHHH    unicode codepoint with hex value HHHH; exactly four hex digits are allowed
`\u` {H+}    unicode codepoint; all hex digits enclosed in {} are used for the codepoint
[manual]: https://nim-lang.org/docs/manual.html#lexical-analysis-string-literals
n/a.

build(semver): change \u7f to \x7f

---

Dockerfile

make it easy to copy chalk into other containers
As chalk is a static binary now there is a no need to release docker image based on any distro as we can just release the raw binary image. This image is not meant to be used directly but is instead meant to be used in other docker builds such as to easily provision docker build images used in CI systems.
Once merged Ill push image to registries
```
docker build -t chalk .
```

build: using scratch for base image of public chalk image

---

CHANGELOG.md
chalk.nimble
src/attestation.nim
src/plugins/awsEcs.nim
src/plugins/cloudMetadata.nim
tests/test_config.py
tests/test_sink.py

```
➜ docker run -it --rm ghcr.io/crashappsec/chalk:0.3.3-dev load https://chalkdust.io/connect.c4m
warn:  ~/.local/chalk/chalk.log: could not resolve sink filename. disabling sink
warn:  default_out: sink is not enabled and cannot be subscribed for topic report
warn:  default_out: sink is not enabled and cannot be subscribed for topic audit
info:  Attempting to load module from: https://chalkdust.io/connect.c4m
error: No SSL/TLS CA certificates found.
```
this will allow chalk to communicate with external APIs even when system has no certs such as in busybox containers
most of the change is in nimutils and then its bubbled up to con4m and chalk
existing tests cover SSL coverage. to test busybox case:
```
➜ docker run -it --rm -v $PWD:$PWD -w $PWD busybox ./chalk --debug load …
```

feat: falling back to mozilla CAs when system has no certs

---

CHANGELOG.md
src/docker_base.nim

https://github.com/crashappsec/chalk/issues/206
looks like even if buildx is installed in older docker versions, --build-context arg is not supported
cant find release docs for this doc so just going by local version experiments. for reference release docs https://docs.docker.com/engine/release-notes/23.0/
```
➜ echo 'FROM alpine' | docker run -i --rm -v ./chalk:/chalk --entrypoint=/chalk -v /var/run/docker.sock:/var/run/docker.sock docker:20.10.24 docker build -t test  -f - .
```

fix(docker): requiring docker >20 for --build-context support

---

CHANGELOG.md
Makefile
chalk.nimble

fixes https://github.com/crashappsec/chalk/issues/194
fixed was in https://github.com/crashappsec/nimutils/pull/46
```
echo foo | ./chalk docker login --password-stdin --username=bar
```

fix: docker login breaks when docker is chalk binary

---

.pre-commit-config.yaml

closes https://github.com/crashappsec/chalk/issues/213
automatically validate/fix py formatting issues in PRs

ci: add black to pre-commit config

---

chalk.nimble
tests/data/configs/docker_cmd.c4m
tests/test_docker.py
tests/utils/docker.py

`docker --version` hangs when `docker` is a chalk binary
previously subprocess run() wasn't being ended in all cases which is fixed now. it surfaced when doing `docker --version` when docker was a chalk binary as there was no IO to wrap in that case command was hanging in the switchboard loop
```
make
cp chalk docker
./docker --version
```

fix: including fix from nimutils for subprocess run

---

CHANGELOG.md
src/attestation.nim

backup service bug in attestion.nim causes segfault
the safeRequest refactor now creates and closes the client which wasnt correctly refactored and wasnt caught.
there are no tests for this and its not easy to add them as it will require adding JWTs in the mix. upcoming refactor for signing keys will refactor this and will make it easier to test this
```
➜ chalk load configs/connect.c4m
➜ rm *.{key,pub}; ./chalk setup --trace
```

fix: segfault in chalk backup service

---

src/collect.nim

this is helpful to see what plugin is currently running as some of them such as tech stack can take some time and otherwise looking at logs you cant tell what is currently running and therefore if its external call timing out or a slow plugin is currently being called

feat: adding log before running plugin

---

CHANGELOG.md
src/confload.nim

containers were failing to startup as `connect.c4m` was changed after the release in the chalkdust bucket
when loading components on chalk startup, if a component was from a URL and had any parameters, it would be re-fetched from the URL again which is not desired as the URL content can change hence causing a failure.
this was caused by loading parameters before loading component source which would initialize the component and if missing would re-fetch it again from URL. By loading source first it removes that possibility.
load components from URL and then ensure they dont change on load

fix: honor $CHALK_COMPONENT_CACHE in confload

---

CHANGELOG.md
chalk.nimble
docker-compose.yml
server/server/api.py
src/reportcache.nim
tests/data/sink_configs/post_http_local.c4m
tests/data/sink_configs/post_https_local.c4m
tests/test_sink.py

https://github.com/crashappsec/nimutils/pull/60
chalk would segfault when accidentally providing `http` scheme to `https` server which would redirect `http`->`https`

fix: fixing sink segfaulting with mismatched http schemes

---

CHANGELOG.md
src/attestation.nim
src/configs/base_report_templates.c4m
tests/test_command.py

fixes https://github.com/crashappsec/chalk/issues/231
withPrivateKey wasnt being honored in all places where cosign key material needed to be loaded:
* it was always trying to load private key even for commands not requiring it
* it didnt load private key for docker command hence docker builds werent being signed
see issue above

fix: loading cosign keys correctly

---

src/configs/chalk.c42spec

fixes https://github.com/crashappsec/chalk/issues/158

doc: fix .cfg -> .c4m extension in docs

---

src/plugins/vctlGit.nim

flaky tests such as https://github.com/crashappsec/chalk/actions/runs/8282914433/job/22664882760
root was was there was unnecessary .strip() and sometimes git objects end with `\n` which is part of a compressed data-stream hence by removing it zips checksum wasnt able to validate which is why it was making some tests flaky which were asserting git plugin keys
looks like chalk v0.3.3 tag ends with newline so interact with chalk repo with that tag being present:
```
➜ cat .git/refs/tags/v0.3.3
fe750922dda1d33c407b41a7aeae7b17acdae78c
➜ cat .git/objects/fe/750922dda1d33c407b41a7aeae7b17acdae78c | hexdump -C | tail -n3
000002f0  c4 33 f5 7d af be 23 df  7d 1a f3 91 df 63 50 ac  |.3.}..#.}....cP.|
00000300  f3 df 26 f2 13 db 38 3e  0a                       |..&...8>.|
00000309
```

fix: chalk not parsing some git ref objects

---

CHANGELOG.md
src/chalk_common.nim
src/commands/cmd_docker.nim
src/docker_base.nim
src/docker_cmdline.nim
src/dockerfile.nim
tests/chalk/runner.py
tests/data/dockerfiles/valid/entrypoint/json.Dockerfile
tests/data/dockerfiles/valid/entrypoint/string.Dockerfile
tests/data/nginx/server.conf
tests/test_command.py
tests/test_composable.py
tests/test_config.py
tests/test_docker.py
tests/test_exec.py
tests/test_git.py
tests/test_plugins.py
tests/test_sink.py

any docker build with `ENTRYPOINT` defined in base image is not wrapped correctly
This recursively looks up entrypoints in all base images
from the dockerfile build target. If ENTRYPOINT/CMD/SHELL
is not found in the dockerfile, base image is inspected
to find that. This allows to correctly wrap all builds
as we know exactly how to wrap existing entrypoints.
This in particular will fix the issue for non-shell
ENTRYPOINTs such as for lambda wrappers which expect
CMD to be a python module argument.
In addition this fixes:
* adding docker statements within the target dockerfile section
boundary. Previously it was always added at the end of Dockerfile
* it honors any --build-arg as passed in via CLI in order
to eval env vars in the Dockerfile (needed for base image inspection)
* improves …

fix(docker): inspecting base images to find entrypoint

---

configs/connect.c4m
src/commands/cmd_docker.nim
src/commands/cmd_exec.nim
src/configs/chalk.c42spec
src/dockerfile.nim
src/util.nim

Instead of requiring --exec-command-name, allowing to extract command name from exec args:
```
chalk exec -- <cmd> [...args]
```
This is controlled by new config `exec.command_name_from_args` which is enabled by default.
This allows to simplify docker wrapping. For example for Dockerfile:
```
FROM alpine
CMD ["foo", "bar"]
```
previously wrapping resulted in:
```
FROM alpine
ENTRYPOINT ["/chalk", "--exec-command-name", "foo", "--"]
CMD ["bar"]
```
As `CMD` was being adjusted, it was not intuitive. By allowing command name to be extracted from args, it allows to wrap with:
```
FROM alpine
ENTRYPOINT ["/chalk", "--"]
CMD ["foo", "bar"]
```

feat: extracting exec command name from args 

---

CHANGELOG.md
src/configs/base_sinks.c4m

fixes https://github.com/crashappsec/chalk/issues/161
as buckets are specific to regions, the parameter should be required to avoid any potential aws API issues as otherwise AWS_REGION env vars might not reflect correct bucket region.
add s3 sink config without region
do we think this is an UX regression? or being explicit in s3 sink config is a good thing? my opinion is that explicit config is better. for example consider docker image wrapped with chalk and its configured to send reports to a bucket in us-east-1 but then the container runs in us-west-1 lambda. Lambda will set `AWS_REGION` to us-west-1 hence  sink default region will be incorrect. thoughts?

fix: requiring region for s3 sinks

---

Dockerfile

tests are failing
https://github.com/sigstore/cosign/issues/3620
looks like hotfixes to cosign v1 are published as :latest tags and there is no v2 tag for grabbing latest v2 cosign versions so pinning to latest v2 for now

build: pinning cosign

---

.github/pull_request_template.md
CHANGELOG.md
src/chalk_common.nim
src/commands/cmd_docker.nim
src/commands/cmd_extract.nim
src/docker_base.nim
src/plugin_api.nim
src/plugins/codecDocker.nim
src/util.nim
tests/Dockerfile

Fixes https://github.com/crashappsec/chalk/issues/247
* disables docker codec if `docker` is not installed which removes the misleading error log on `chalk exec`
* explicitly falling back to `docker` command for better stderr when `docker` is not installed during `chalk docker ...`

fix: error docker inspect logs during chalk exec

---

CHANGELOG.md
src/confload.nim
src/util.nim
tests/test_docker.py
tests/utils/docker.py

unable to execute docker command which has "docker" as an arg somewhere in the params
https://github.com/zaproxy/zaproxy/actions/runs/8452961393/job/23155525385#step:9:482
previously "docker" was only wrapped when "docker" was not present anywhere in the flags. That is a bad assumption as for example a valid docker context can be a folder "docker". Right now if the exe name is "docker" its always appended to the CLI params hence allowing chalk to correctly validate CLI args.
```
➜ make tests args="test_docker.py::test_docker_context --logs"
```

fix: docker command name is honored while wrapping docker exe

---

CHANGELOG.md
chalk.nimble
tests/test_docker.py

https://github.com/crashappsec/nimutils/pull/65
Running `chalk docker ...` when `docker` is not installed would not exit with appropriate exit code.
run `chalk docker ...` without `docker` being on `PATH`

fix: runCommand returns non-zero exit code for non-existing exes

---

CHANGELOG.md
src/configs/chalk.c42spec
src/docker/platform.nim
tests/functional/data/configs/docker_wrap.c4m

As setup-chalk-action allows to download chalks pinned by their commit build, by only downloading chalk from a single release url, it will potentially break multi-platform builds. By attempting to download from a release url first and if failed downloading from a commit build it will allow chalk to fully function both with release and pre-release builds without requiring to update user-configs.
```
➜ make tests args="test_docker.py::test_multiplatform_build[valid/sample_1-True]"
```

feat: allow to download chalk by multiple urls

---

CHANGELOG.md
src/plugins/cloudMetadata.nim

Fixes https://github.com/crashappsec/chalk/issues/298
This PR adds an additional check for presence of cloud run-services in the vendor check. Cloud run instances lack vendor info in /sys, therefore we rely on the combined presence of dedicated environment variables and `google.internal` appearing in /etc/resolv.conf
Deploy a chalked image to GCP and ensure we get back desired metadata

fix: detect cloud run services without vendor info

---

CHANGELOG.md
src/configs/base_chalk_templates.c4m
src/configs/base_keyspecs.c4m
src/configs/base_plugins.c4m
src/configs/base_report_templates.c4m
src/configs/crashoverride.c4m
src/plugins/ciGithub.nim
src/plugins/ciGitlab.nim
tests/functional/imds/app.py
tests/functional/test_plugins.py

fixes https://github.com/crashappsec/chalk/issues/261
Will allow to uniquely identify a repo as ORIGIN_URI is not guaranteed to be unique. Note this only works in CI systems which support functionality and therefore wont work everywhere such as in Jenkins.
```
➜ make tests args="test_plugins.py::test_github"
➜ make tests args="test_plugins.py::test_gitlab"
```

feat: BUILD_ORIGIN_ID/KEY and BUILD_ORIGIN_OWNER_ID/KEY keys

---

CHANGELOG.md
src/configs/chalk.c42spec
tests/functional/data/configs/custom_keys.c4m
tests/functional/test_config.py

key validation enforced custom keys to start with `X-` or `_X-` which is invalid con4m syntax. Changing to `X-` and `_X_`.
Also adding test case how custom keys can be added to reports and chalk marks.
```
➜ make tests args="test_config.py::test_custom_keys"
```

fix: fixing chalk custom keys validation

---

CHANGELOG.md
chalk.nimble

macos builds were failing in some cases
downloading root cert url was not quoted correctly in curl command
run build on mac

fix: macos certs download url was not quoted

---

CHANGELOG.md
src/configs/base_keyspecs.c4m
src/configs/base_plugins.c4m
src/configs/base_report_templates.c4m
src/configs/chalk.c42spec
src/configs/crashoverride.c4m
src/plugins/cloudMetadata.nim
tests/functional/data/configs/resolv.c4m
tests/functional/imds/app.py
tests/functional/test_plugins.py

Additional improvement over https://github.com/crashappsec/chalk/issues/298
Project information is not included in the instance metadata, therefore this exposes a separate key `_GCP_PROJECT_METADATA` with project info, if one is found
Deploy a chalked image to GCP and check that project metadata is populated

feat: add _GCP_PROJECT_METADATA key

---

CHANGELOG.md
src/selfextract.nim
tests/functional/data/configs/validation/valid_2.c4m
tests/functional/test_config.py

fixes https://github.com/crashappsec/chalk/issues/312
test config function reloads all cached components which means if previously cached component would be reloaded, the test funcion would reload its previous definition hence not actually testing the new definition. By ignoring the component to be loaded, this ensures the new definition is not replaced by anything hence all components can be successfully validated.
```
➜ make tests args="test_config.py::test_load_valid_then_invalid --pdb"
```

fix: chalk load revalidates already cached components

---

CHANGELOG.md
src/con4mfuncs.nim
src/configs/base_keyspecs.c4m
src/configs/sastconfig.c4m
src/configs/sbomconfig.c4m
src/plugins/externalTool.nim
src/util.nim
tests/functional/data/configs/composable/valid/sast/enable_sast.c4m
tests/functional/data/configs/composable/valid/sboms/enable_sboms.c4m
tests/functional/test_plugins.py
tests/functional/testing.c4m

previously chalk would always try to install the external tool on the host system which in some cases required some system dependencies like `pipx` or `python3` to be available for `semgrep`. Right now the precedence is:
1. use installed tool
2. use docker (if present)
3. install tool
This should minimize any external system dependencies and should allow to bundle any tool configs in a container which can be customized via the config:
```
tool.syft.syft_container = "mysyft:latest"
```
In addition some logging was improved in tool runtime to help in debugging what tool ran and what keys it generated.
Also `semgrep ci` does not allow to specify target for scanning which means that it was always scanning `cwd()` which is incorrect for example in case of docker builds when context is outside …

feat: external tools if not installed run via docker

---

CHANGELOG.md
src/docker/build.nim
src/docker/entrypoint.nim
src/docker/wrap.nim
tests/functional/test_docker.py

When docker context contained `docker` or `chalk` folders, entrypoint wrapping would fail
For non-buildx build, as the file needed to be copied into the context to be copied in Dockerfile, the name needs to be unique as if the same filename/folder already exist in the context folder, the copy/move will fail which in turn would bail out of ENTRYPOINT wrapping. Now chalk ensures that filename is unique for both copy/move modes.
In addition when using buildx, whenever chalk binary was located in a folder which contained .dockerignore which ignored the `chalk` binary (e.g. in chalk repo itself), the wrapping would fail as the binary could not be copied into the build. Now this edge case is detected and the file is copied into a temporary directory hence guaranteeing there is no .dockerignore …

fix: docker non-buildx file copy ensure name is unique

---

CHANGELOG.md
src/docker/exe.nim
src/docker/wrap.nim
tests/functional/test_docker.py
tests/unit/test_semver.nim

when using distroless image without buildx, some builds can fail
When chalk needs to copy both `/chalk.json` and `/chalk` in the build, it needs to set correct permissions on the file. Without buildx, as it cannot leverage `COPY --chmod`, Chalk needs to manually adjust permissions by:
```
COPY chalk.json /chalk.json
RUN chmod 0444 /chalk.json
```
However for distroless images `RUN` cannot work as there is no `chmod` executable and so the build will fail.
Now for this case we attempt to use multi-stage builds if possible as we can use `busybox` image which has the capability to run `chmod` and then we copy that into the final image. Something like:
```
FROM busybox AS chalk_json
COPY chalk.json /chalk.json
RUN chmod 0444 /chalk.json
FROM scratch
COPY --from=chalk_json /chalk.json …
```

fix(docker): build without buildx with non-root user

---

CHANGELOG.md
src/docker/extract.nim
tests/functional/chalk/runner.py
tests/functional/test_docker.py

Image build without buildx on `docker push` its chalk mark was not reported
The format of `docker history` is different between buildx and non-buildx images. For non-buildx:
```
/bin/sh -c #(nop) COPY file:283b357328fb308cf6cfe240564dab744e8547f48c8626f11c1926ce41df45ef in /chalk.json
```
For buildx:
```
COPY --chmod=0444 chalk-XP9wJMFN-file.tmp /chalk.json # buildkit
```
To try to accomodate both chalk now simply checks for substring match whether `"COPY "` and `" /chalk.json"` was present in the layer spec and if so it attempts to extract chalk mark from the image tar file.
```
➜ make tests args="test_docker.py::test_build_and_push[valid/empty-False-False] --logs"
```

fix(docker): extracting chalk mark from distroless non-buildx images

---

src/configs/base_keyspecs.c4m

no impact to anything. chalk was still reporting it correctly. just a warning message
there are warnings:
> warn: docker: JSON key Config.OnBuild associated with chalk key
> '_IMAGE_ONBUILD' is not of the expected type. Using it anyway.
the key has an incorrect type. ONBUILD must be an array but chalk was defining it as a string

fix: _IMAGE_ONBUILD is a list, not a string

---

CHANGELOG.md
src/configs/base_chalk_templates.c4m
src/configs/base_keyspecs.c4m
src/configs/base_plugins.c4m
src/configs/base_report_templates.c4m
src/configs/crashoverride.c4m
src/plugins/ciGithub.nim
src/plugins/ciGitlab.nim
src/plugins/ciJenkins.nim
tests/functional/test_plugins.py

this should allow to at find the commit id of the build in case chalk could not interact with the .git folder.
```
➜ make tests args="test_plugins.py::test_github test_plugins.py::test_gitlab"
```

feat: BUILD_COMMIT_ID key

---

CHANGELOG.md
src/plugins/vctlGit.nim
tests/functional/test_git.py
tests/functional/utils/git.py

chalk does not report `COMMIT_ID` for branches with `/` in them
If the branch is "foo/bar", chalk incorrectly split the branch name and therefore was only attempting to find commit id for branch "foo" which is incorrect.
```
➜ make tests args="test_git.py::test_repo --logs -x"
```

fix(git): handle branch names with /

---

CHANGELOG.md
src/plugins/vctlGit.nim
tests/functional/test_git.py
tests/functional/utils/git.py

annotated tags are not reported when cloning repo in CI (github)
fixes https://github.com/crashappsec/chalk/issues/332
fixes https://github.com/crashappsec/chalk/issues/342
Packed git object does not store normal object header.
When reading file from the pack, chalk now adds back normal object
header for consistent parsing so its irrelevant where the object
content was grabbed from.
In addition `git pack-refs` packs all refs in .git/refs/ into
.git/packed-refs which chalk now honors as well.
Otherwise chalk would presume it was an empty git repo.
```
✗ make tests args="test_git.py::test_repo --logs -x"
```

fix(git): git packed objects/refs

---

CHANGELOG.md
src/plugins/vctlGit.nim
tests/functional/test_git.py
tests/functional/utils/git.py

wrong commit id is reported
`.git/HEAD` can be a symbolic ref to a branch/tag or directly pointer to a commit. When doing `git checkout <branch>` it normally sets it to symbolic ref however when doing `git checkout <tag>` it usually sets it directly to the tag's commit. However it is possible to update it via `git symbolic-ref HEAD <tag>`. In that case `HEAD` will point to annotated tag and as such we chalk simply opens the ref of that symbolic ref it is not guaranteed to be for a commit id. Now chalk loads the tag object and if it is an annotated tag, resolves commit id to be from the tags object pointer.
```
➜ make tests args="test_git.py::test_repo[False-copy_files0-True-None-True-True] --logs -x"
```

fix(git): commit id is correctly determined for annotated symbolic ref tags

---

CHANGELOG.md
src/configs/base_init.c4m
src/configs/chalk.c42spec
src/docker/git.nim
src/git.nim
src/plugins/vctlGit.nim
tests/functional/test_git.py
tests/functional/utils/git.py

fixes https://github.com/crashappsec/chalk/issues/345
If repo is checked out incorrectly locally, a tag can be lightweight but annotated in origin. To guarantee chalk sees up-to-date tags, chalk refetches lightweight tags to ensure it reports correct metadata about the "latest" tag.
This was noticed via checkout github action which if triggered from a tag build it looses any tag annotations.
```
➜ make tests args="test_git.py::test_refetch_tag --logs --pdb"
```

fix: refetching lightweight tags from origin

---

CHANGELOG.md
src/chalk_common.nim
src/docker/git.nim
src/util.nim
tests/functional/test_docker.py

fixes https://github.com/crashappsec/chalk/issues/350
Docker supports providing full refspec as the context.
For example:
```
docker build https://github.com/user/repo.git#refs/pull/1/merge
```
Previously chalk only supported tags and branches:
```
docker build https://github.com/user/repo.git#<branch>
docker build https://github.com/user/repo.git#<tag>
```
Now chalk also fetches any other explicit refs passed to it.
```
➜ make tests args="test_docker.py::test_git_context --slow -x --logs"
```
tests:--slow

fix(docker): generic git refspec in context

---

CHANGELOG.md
src/plugins/vctlGit.nim
tests/functional/test_git.py
tests/functional/utils/git.py

fixes https://github.com/crashappsec/chalk/issues/353
```
➜ make tests args="test_git.py::test_repo -x --logs"
```

fix: support git empty tag messages

---

CHANGELOG.md
src/docker/build.nim
src/docker/exe.nim

chalk build fails due to invalid `--metadata-file` flag.
In older docker versions, as `docker build` is not an alias to `docker buildx build`, `--metadata-file` flag is not supported. It only works when explicitly using `docker buildx build` in which case 0.6.0 is required which added that flag. Otherwise docker version needs to be >=22 which aliased `build` to `buildx build` as well as have supported buildx version.
No easy way of testing it in CI but tested locally various combination of versions.
Was running something like:
```
➜ echo '
FROM docker:22.06-rc
COPY --from=docker/buildx-bin:0.6.0 /buildx /usr/lib/docker/cli-plugins/docker-buildx
COPY --from=docker/buildx-bin:0.6.0 /buildx /usr/local/libexec/docker/cli-plugins/docker-buildx
' | docker build -f - . -t dockerbuildx
and docker …
```

fix(docker): fixing --metadata-file support

---

tests/functional/testing.c4m

small test improvement. saw in one of the test runs that usage metrics were being sent to prod env:
```
error: Call to 'connect' timed out.: [ { "_OPERATION" : "build", "_TIMESTAMP" : 1720570114938, "_OP_CHALKER_COMMIT_ID" : "5c50ce0ea987b025645658c18da18f508388737a", "_OP_CHALKER_VERSION" : "0.4.8-dev", "_OP_PLATFORM" : "GNU/Linux x86_64", "_OP_CHALK_COUNT" : 1 } ]
(sink conf='usage_stats_conf')
uri          = https://chalk.crashoverride.run/v0.1/usage
content_type = application/json
timeout      = none
headers      = none```
https://github.com/crashappsec/chalk/actions/runs/9865853999/job/27243572497?pr=365

test: sending usage reports to test env in tests

---

src/plugins/cloudMetadata.nim

Implementing https://github.com/crashappsec/chalk/commit/55cd0d52035251de461abb1599821ceb2200f374 reminded me that we'd benefit from tidying up this file. We've been having some issues with `_OP_CLOUD_PROVIDER`, and it'd help if this file was easier to reason about.
There was previously one long function that handled collecting metadata for AWS, Azure, and GCP, which had to return after setting metadata for one platform. Split into separate functions, and add an enum to resolve the `FIXME`s.
We can refactor further later - this PR is just an attempt at a quick step in the right direction.
Also resolve some nits. See individual commits.
Verify that this is refactoring-only. I might have missed something with how the AWS metadata collection worked.

refactor(cloudMetadata): refactor metadata collection

---

CHANGELOG.md
src/plugins/cloudMetadata.nim
src/run_management.nim

some keys were not guaranteed to be present and timeout errors were not handled in the plugin
When making HTTP calls the plugin did not handle timeout exceptions and
as such on any exception complete plugin will bail and none of its keys
were populated such as `_OP_CLOUD_METADATA`. We were observing a bunch
of logs:
```
warn:  When collecting run-time host info, plugin implementation cloud_metadata threw an exception it didn't handle: Call to 'connect' timed out.
```
Looks like 250ms wasnt enough in AWS for metadata plugin to reliably hit
metadata endpoint so bumping it to 500ms.
---
metadata endpoint can fail due to timeout however in most cases we can
still determine service type by the presence of env vars plus the
hardware vendor file already told us the cloud provider so we can set …

fix: cloud metadata timeout handing and guaranteeing _OP_CLOUD_* keys

---

CHANGELOG.md
README.md

got `vale` running on my machine again and these popped up

docs: typos found by vale

---

CHANGELOG.md
src/configs/base_outconf.c4m

currently default docker chalk template is `minimal` which does not include any information about the repository, etc. That makes it harder to process any out of order events such as `exec` coming in before `build` for whatever reason (network latency, etc). By bundling the repo information into the chalkmark itself it makes `exec` reports a lot less dependant on the `build` report. Also makes for more pleasant experience manually pulling the image and inspecting its `/chalk.json`.

feat: using mark_default for docker chalk templates

---

CHANGELOG.md
src/chalk_common.nim
src/configs/base_keyspecs.c4m
src/configs/base_report_templates.c4m
src/configs/crashoverride.c4m
src/docker/build.nim
src/docker/dockerfile.nim
src/run_management.nim
tests/functional/data/dockerfiles/valid/bases/Dockerfile
tests/functional/test_docker.py

currently chalk only reports a single base image
fixes https://github.com/crashappsec/chalk/issues/375
chalk can report all images used across all of the dockerfile across all of the targets/sections including `COPY` directives
```
➜ make tests args="test_docker.py::test_base_images --logs"
```

feat: reporting all base images within Dockerfile

---

chalk.nimble
src/docker/manifest.nim
src/www_authenticate.nim

authSafeRequest will be used by registry SDK as www-authenticate
is a common auth mechanism in registries including docker hub:
```
➜ curl https://registry-1.docker.io/v2/ -Is | grep authenticate
www-authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io"
```
In addition the token headers are cached by hostname so that only first
failure needs to elicit the auth after which same token is reused
multiple times
```
➜ make tests args="test_docker.py::test_base_ecr --logs"
```

refactor: moving out www-authenticate handling to authSafeRequest 

---

CHANGELOG.md
src/docker/entrypoint.nim
tests/functional/test_docker.py

building image on top of another chalk image breaks its runtime
base image ENTRYPOINT wrapping was always wrapping it regardless of its existing value which meant that chalk can recursively wrap itself which would always fail at run-time.
now we check if the entrypoint is already wrapped with chalk and if so skip wrapping ENTRYPOINT again
```
➜ make tests args="test_docker.py::test_recursion_wrapping --logs"
```

fix: recursively wrapping docker ENTRYPOINT

---

CHANGELOG.md
src/plugins/cloudMetadata.nim

we are still seeing some connect timeouts with 500ms

fix: increasing cloud metadata timeout

---

CHANGELOG.md
src/configs/ioconfig.c4m
tests/functional/testing.c4m

`./chalk exec` shows report in stdout for interactive shell
`./chalk exec` .. should preserve original command output
for example running docker wrapped container:
```
docker run --rm -it python-wrapped-with-chalk
```
would show full chalk exec report which would be unexpected

fix: hiding chalk exec report in interactive shell

---

chalk.nimble

this was impacting release as macos arm could no longer build

build: buping con4m to include macos runner fixes for latest clang

---

tests/functional/chalk/runner.py
tests/functional/test_docker.py
tests/functional/utils/docker.py

changed semantic of dockerfile param in docker build wrappers which broke some --slow tests so adding new param content now. In theory we could rename dockerfile to dockerfile_path and dockerfile params but that would require changing all existing callers which is bigger refactor we can opt in to do in the future. For now content param should suffice.
tests:--slow

test: fixing integration tests

---

CHANGELOG.md
src/collect.nim
src/docker/collect.nim
src/docker/exe.nim
src/plugins/procfs.nim

some metadata is missing
Internally to get buildx builder info, it needs to find out the builder name which was referencing an attribute only accessible for docker build command
To catch plugin errors in the future switching that log to `error` level which automatically fails tests if the plugin fails.
```
➜ make tests args="test_docker.py::test_build_and_push --logs"
```

fix: fixing docker plugin run-time collection for non-build cmd

---

chalk.nimble

sometimes aws returns permission denied for sts get-caller-identity
we are seeing sometimes aws errors, specifically with sts get-caller-identity. Adding retries can help to ensure the request eventually succeeds.
cant replicate issue

build: bumping con4m for aws client retries

---

CHANGELOG.md
src/docker/collect.nim
tests/functional/test_docker.py

`_IMAGE_DIGEST` is missing for `docker push` without buildx
this will be handled better when registry SDK is merged/fully used everywhere however for now this specifically addresses `_IMAGE_DIGEST` field when buildx is missing
```
➜ make tests args="test_docker.py::test_push_without_buildx --logs --pdb"
```

fix: sending _IMAGE_DIGEST for push without buildx

---

CHANGELOG.md
src/docker/build.nim
src/docker/inspect.nim
tests/functional/test_docker.py

`_REPO_DIGESTS` does not match between `docker build && docker push`
metadata file misreports image config digest as image digest which is not valid but oh well. As chalk was using that value to normalize digest value for `_REPO_DIGESTS` it was then misreporting image id as the digest.
```
➜ make tests args="test_docker.py::test_build_and_push --logs --pdb"
```

fix: _REPO_DIGESTS misreported for buildx builds

---

CHANGELOG.md
src/docker/push.nim
src/plugins/system.nim
tests/functional/test_docker.py

wrong fields were sent in the report
these 2 fields were different:
* `TIMESTAMP_WHEN_CHALKED` was being overwritten hence changing the hash
* `DOCKER_PLATFORM` was not forced during `docker push` as in `docker build` which meant that it was ignored in computing the hash
```
➜ make tests args="test_docker.py::test_build_and_push --logs --pdb"
```

fix: docker push generated wrong METADATA_* keys

---

tests/functional/chalk/runner.py
tests/functional/utils/docker.py
tests/functional/utils/os.py

looks like in some cases tmp file was garbage collected earlier than the process exit which resulted in :
```
ERROR: failed to solve: failed to read dockerfile: open tmp_76z0fet: no such file or directory
```
passing content as stdin should make that irrelevant however if well need to do any contextual cleanup as part of cmd handling also moved it as a context manager which will allow us to cleanup anything necessary after the full command is finished executing
also in some cases stderr did not match between the commands as it included the failure timestamp so no longer comparing it as part of the program equality logic
example failures:
https://github.com/crashappsec/chalk/actions/runs/10356433406/job/28667491174?pr=403
https://github.com/crashappsec/chalk/actions/runs/10356433406/job/286 …

test: fixing flaky test

---

chalk.nimble
src/plugins/awsEcs.nim
src/plugins/cloudMetadata.nim

by the time we attempt any request to AWS, we already know we are running in instance which should respond successfully so multiple retries should help with unstable network conditions which we see in some reports

feat: retrying all aws requests even on connect timeout

---

CHANGELOG.md
src/plugins/conffile.nim

empty keys were sent from conffile plugin
this did not match other plugins

fix: conffile plugin was sending empty keys

---

CHANGELOG.md
src/configs/chalk.c42spec
src/plugins/cloudMetadata.nim
tests/functional/conf.py
tests/functional/conftest.py
tests/functional/data/configs/imds.c4m
tests/functional/imds/app.py
tests/functional/test_plugins.py
tests/functional/utils/tmp.py

sometimes cloud metadata endpoint is not reachable which doesnt allow Chalk to query all the relevant metadata such as its instance ID. Chalk now attempts to get the instance id from the sys board asset tag file (if present) before looking up rest of the cloud metadata.
```
➜ make tests args="test_plugins.py::test_aws_no_imds --logs"
```

fix: looking up ec2 instance id from board_asset_tag

---

CHANGELOG.md
chalk.nimble

AWS lambda ARN was not reported for non-us-east-1 regions
accessing sts via global endpoint which is equivalent to us-east-1 doesnt allow to access region-specific tokens hence the need to use region-specific endpoints
test lambda in another region

build: bumping nimutils/con4m for aws region-specific endpoint fix

---

CHANGELOG.md
src/commands/cmd_docker.nim
src/configs/base_keyspecs.c4m
src/configs/base_plugins.c4m
src/configs/crashoverride.c4m
src/docker/base.nim
src/docker/build.nim
src/docker/push.nim
src/plugins/system.nim
src/util.nim
tests/functional/data/configs/docker_wrap.c4m
tests/functional/test_docker.py
tests/functional/testing.c4m

its hard to say the reason why docker build report doesnt have any chalkmarks without any specific error indicators
this is especially useful for when chalk invoked external commands such as for docker build chalk reports final exit code which can be insightful whenever external command fails
run tests for `test_docker.py` file

feat: adding _OP_EXIT_CODE key

---

Dockerfile
tests/functional/Dockerfile

This changes the Dockerfile to pull the cosign container image from GHCR instead of Google Cloud. This helps the Sigstore team manage their cloud spend (as GHCR is provided for free and Google Cloud Artifact Registry is not).
Note the container hash does not change and images are posted to both locations upon cosign's release process.

build(common): switch cosign registry from GCR to GHCR

---

.github/workflows/tests.yml
CHANGELOG.md
Dockerfile
Makefile
chalk.nimble
config.nims
src/configs/base_init.c4m
src/configs/base_keyspecs.c4m
src/configs/base_plugins.c4m
src/configs/base_report_templates.c4m
src/configs/chalk.c42spec
src/configs/crashoverride.c4m
src/pingttl.nim
src/plugin_load.nim
src/plugins/network.nim
tests/functional/Dockerfile
tests/functional/test_plugins.py
tests/functional/testing.c4m

get some metadata when imds ip endpoint cannot be reached
This will allow to get transient IP addresses along the NAT route so that we can fetch intermediate IPs from within docker containers which might not be accessible otherwise. For example it can be used to get the subnet gateway IP which is not otherwise available as within the docker container unless its running with host networking chalk can only get the docker network private IP address. This should be useful in figuring out where within the network container is running.
```
➜ make tests args="test_plugins.py::test_network --logs"
```

feat: adding pingttl util

---

CHANGELOG.md
src/configs/base_keyspecs.c4m
src/configs/base_plugins.c4m
src/configs/base_report_templates.c4m
src/configs/crashoverride.c4m
src/docker/build.nim
src/plugins/vctlGit.nim
src/util.nim
tests/functional/test_docker.py

Provides the `DOCKERFILE_PATH_WITHIN_VCTL` chalk key with the relative path of the Dockerfile to the version control system's project root. If that path is outside the project or the Dockerfile was provided via `stdin`, the key is omitted.
Run relevant tests with:
```bash
make tests args="test_docker.py"
```

feat: report relative path of Dockerfile

---

chalk.nimble
src/chalk.nim

#435 
Added the ability to compile chalk with nim's profiling support. 
To compile w/ execution time support, run 'nimble performance'.
For memory profling, run 'nimble memprofile'.
You cannot turn both on at once (Nim doesn't allow it).
The resulting chalk binary will, on exit, drop 'profile_results.txt' in the directory from which Chalk is run.
The overhead for nim profiling seems like it might be high :/
Follow the above instructions and profile some stuff.

feat: Option to build with profiling

---

CHANGELOG.md
src/configs/sastconfig.c4m

when docker is not available, installed semgrep via chalk cannot run
starting with 1.94.0, if semgrep is not on PATH, its not able to run and throws:
```
Error: exception Unix_error: No such file or directory execvp pysemgrep
```
related issue https://github.com/semgrep/semgrep/issues/10652
```
➜ make tests args="test_plugins.py::test_semgrep[sample_1-False] --logs --pdb"
```

fix: semgrep needs to be on PATH

---

CHANGELOG.md
configs/co/heartbeat.c4m
configs/co/sast.c4m
configs/co/sbom.c4m
src/configs/base_keyspecs.c4m
src/configs/base_outconf.c4m
src/configs/base_plugins.c4m
src/configs/base_report_templates.c4m
src/configs/crashoverride.c4m
src/plugins/system.nim
tests/functional/data/configs/docker_heartbeat.c4m
tests/functional/test_docker.py

Default heartbeat report is too large as it uses the default report which is quite heavy for simple liveliness checks
This adds minimal report template for heartbeats which simply reports exec id (to tie to exec report) as well as other basic metadata such as metadata id, operation, timestamp, etc.
Will be enabling it by default specifically for co config later.
```
➜ make tests args="test_docker.py::test_docker_heartbeat --logs --pdb"
```

feat: heartbeat minimal report template

---

CHANGELOG.md
src/collect.nim
src/configs/base_plugins.c4m
src/docker/push.nim
src/plugins/system.nim
tests/functional/test_docker.py
tests/functional/testing.c4m
tests/functional/utils/docker.py

push report for non-chalked image had some keys missing such as `_CHALK_RUN_TIME`
currently metsys plugin was reporting global metadata keys such as chalk run time as well as generating attestation bits such as artifact signature.
this meant that disabling metsys plugin to avoid assigning metadata id, etc would also not report global keys such as chalk run time
this was happening for docker push when pushing non-chalked image
```
➜ make tests args="test_docker.py::test_push_nonchalked --logs"
```

fix: split attestation bits from metsys plugin

---

CHANGELOG.md
src/plugins/externalTool.nim
tests/functional/chalk/validate.py
tests/functional/test_plugins.py

SBOM key was reported both on report and chalk mark level:
```json
{
"_CHALKS": {"SBOM": {...}},
"SBOM": {...}
}
```
Some tools work on context directories (e.g. sbom) and for non-fs artifacts (e.g. docker image), sbom tool would run both during host chalk time as well as artifact chalk time collections. As both would collect its output for the same path input, it would produce duplicate output in both report and chalk mark levels.
Now any tool can run at most once and any future attempts for the same path are skipped which removes duplicate keys.
```
➜ make tests args="test_plugins.py::test_syft_docker --logs"
```

fix: external tools producing duplicate keys

---

.gitignore
Makefile
docker-compose.yml

could not do memory profile builds via docker
also `make debug` stripped binary which is not correct
all tasks which have "build" in their description will be automatically wrapped by make
also passing DEBUG in compose so that make debug does not strip in docker builds
```
make debug
make memprofile
```

build: wrapping all nimble build targets in make

---

server/server/api.py
tests/functional/chalk/runner.py
tests/functional/test_sink.py

when sink fails it should cache report but proceed as usual
we have seen a possibly hanging chalk after 500 in a sink
adding test case for when sink errors with 500, rest of the chalk report proceeds as needed
```
➜ make tests args="test_sink.py::test_500_http_fastapi --logs --pdb"
```

test: adding test for 500 sink

---

CHANGELOG.md
chalk.nimble
src/chalk.nim
src/chalk_common.nim
src/commands/cmd_exec.nim
src/plugin_api.nim
src/plugins/awsEcs.nim
src/plugins/awsLambda.nim
src/plugins/codecMacOs.nim
src/plugins/codecZip.nim
src/plugins/externalTool.nim
src/plugins/procfs.nim
src/plugins/system.nim
src/plugins/vctlGit.nim
src/run_management.nim

chalk running in as daemon with heartbeats had ever-increasing memory footprint
Each heartbeat report, it would send HTTP request to chalk api. That was done via `safeRequest` from nimutils which would initialize `SslContext`. That context included all root CA certs/etc and would use ~1Mb on average. At the end of the request, it wasnt correctly discarded as nim would GC its reference however it would call into openssl functions to clear all the inner data-structures. Now we explicitly destroy the context after each request to ensure its memory is correctly cleared.
for more:
https://github.com/crashappsec/nimutils/pull/81
Run long running process with heartbeats enabled and check its memory utilization.

fix: safeRequest memory leak

---

CHANGELOG.md
src/attestation/embed.nim
tests/functional/chalk/runner.py
tests/functional/test_command.py
tests/functional/utils/os.py

it is possible to accidentally generate new keys in CI where it is not desirable.
follow up to https://github.com/crashappsec/chalk/pull/445
```
➜ make tests args="test_command.py::test_setup --logs"
```

feat: require TTY to generate new keys in chalk setup

---

docker-compose.yml
src/docker/ids.nim
src/docker/registry.nim
src/util.nim
tests/functional/conf.py
tests/functional/data/templates/docker/buildkitd.toml
tests/functional/data/templates/docker/daemon.py
tests/functional/test_docker.py
tests/unit/test_docker_ids.nim

adds support for mirrors in both docker daemon config as well as buildx node configs
Whenever mirror is configured, docker pulls images from the mirror unless there is an error in which case it falls back to the upstream registry. Chalk should match that behavior so that we can both interact with the registries in the same manner as docker as well as in the future be able to report metadata about registry use more accurately.
```
➜ make tests args="test_docker.py::test_base_registry --logs"
```
**note** this is PR to upstream `registry` branch

feat: adding docker registry mirrors support

---

chalk.nimble
src/attestation_api.nim
src/chalk_common.nim
src/docker/collect.nim
src/docker/extract.nim
src/docker/ids.nim
src/docker/json.nim
src/docker/manifest.nim
src/docker/registry.nim
tests/functional/data/templates/docker/daemon.py
tests/functional/testing.c4m

chalk can extract chalk mark from either:
* in-toto attestation layer
* last layer directly from registry
this will be necessary for base image inspection as well as dropping cosign dep in the future
also now we can directly grab provenance/sbom from the registry
run `test_docker.py` tests. all existing functionality should still work as-is

refactor: extracting chalk mark from registry

---

CHANGELOG.md
src/chalk_common.nim
src/docker/build.nim
src/docker/cmdline.nim
src/docker/manifest.nim
src/util.nim
tests/functional/test_docker.py

If the contents of a Dockerfile is passed via stdin (e.g. FROM alpine | chalk build) the key reporting the relative path should be dropped.
The predicates that would trigger the dropping of `DOCKERFILE_PATH_WITHIN_VCTL` were insufficient in the case where a Dockerfile's contents was provided via a pipe (e.g., `FROM alpine | chalk docker build -f - .`). This resulted in the reporting of values like `:stdin:` or `some/path/:stdin:`.
make tests args="test_docker.py::test_piped_dockerfile_has_no_relative_path --logs

fix: DOCKERFILE_PATH_WITHIN_VCTL cannot have :stdin: as value

---

CHANGELOG.md
src/collect.nim
src/commands/cmd_extract.nim
src/docker/build.nim
src/docker/push.nim
src/docker/scan.nim
src/run_management.nim
tests/functional/test_docker.py

not all logs were showing up in `_OP_ERRORS`
without context manager it was a manual process which was setting the current error object which is responsible for populating either _OP_ERRORS or ERR_INFO keys. As such for example during docker build, as soon as chalk was starting subscan of the docker binary, its target was switched to the docker binary chalk object hence no more logs were collected for `_OP_ERRORS` even after subscan was complete.
Now operations explicitly have to use context manager to limit the scope of the current error object hence guaranteeing scope is always reverted to the original object. Docker collection is more involved due to multi-platform builds as a single base-chalk is used to create possibly many subplatform chalk objects hence the context manager is …

fix: context manager to scope logs collection for _OP_ERRORS and ERR_INFO

---

CHANGELOG.md
src/chalk_common.nim
src/configs/base_keyspecs.c4m
src/configs/buildkitcmd.c4m
src/configs/chalk.c42spec
src/docker/exe.nim
src/docker/nodes.nim
src/docker/registry.nim
src/plugins/codecDocker.nim
tests/functional/chalk/runner.py
tests/functional/entrypoint.sh
tests/functional/test_docker.py
tests/functional/utils/docker.py

possible sefault with empty builder node config
not all build nodes have a config file associated with them and as such buildkitd.toml might not exist. That doesnt mean the node doesnt exist, it simply means it has no custom config.
For example:
```
docker buildx create test
```
To correctly detect whether a node has a config or not, the container entrypoint/cmd are inspected to find the corresponding `--config` and if present, only then attempts to read the node config. Otherwise empty config is used.
This also surfaced a segfault when using empty config the code was assuming ["registry"] was always present which is not the case.
As the node code now needed to inspect the container args, moved node-related logic to separate nodes.nim therefore allowing it to reference inspect.nim as …

fix: empty buildx node config

---

.github/workflows/tests.yml
.github/workflows/unit-tests.yml
CHANGELOG.md
docker-compose.yml
src/configs/base_keyspecs.c4m
src/configs/base_report_templates.c4m
src/configs/crashoverride.c4m
src/docker/build.nim
src/docker/collect.nim
src/docker/ids.nim
tests/functional/test_docker.py
tests/functional/test_plugins.py
tests/functional/utils/dict.py

report repo URL whenever possible or compute it for Docker Hub. chalk can add support for more registries in the future.
also populating image creating timestamp from the OCI annotation to report more metadata about non-chalked base images
```
➜ maketest test_docker.py::test_base_images --pdb --logs
```

feat: _REPO_URLS key

---

CHANGELOG.md
src/docker/build.nim
src/docker/collect.nim
src/docker/dockerfile.nim
tests/functional/test_docker.py

some build are taking much much longer to run with 0.5.0
for example https://github.com/zaproxy/zaproxy/actions/runs/12799538079/job/35702879563 is ~3h vs normal 20min.
thank you @psiinon for the report
there are cases where the base image platform might not match the build target platform where chalk was not honoring it
for example for multi-platform builds:
```
FROM --platform=linux/amd64 ubuntu AS builder
RUN build.sh
FROM scratch
COPY --from=builder /app /app
```
If the app build is arch-agnostic (e.g. Java), sometimes its much faster for multi-platform builds to pin the builder to specific platform however chalk was not honoring the `--platform` when pinning the base image.
Also fixing a minor `_REPO_URLS` incorrectly sourcing image annotation.
```
➜ maketest …
```

fix: honoring --platform for base image pinning

---

CHANGELOG.md
src/docker/collect.nim
tests/functional/test_docker.py

`_REPO_TAGS` are missing all tags when using `docker buildx --push`
In order to reduce registry interactions, only unique repo digests are interacted with however that meant that if the same image was tagged with multiple tags, its tags were lost as the locally loaded RepoTags will be missing all other tags. The fix is simply concatenate all given tags when processing tags.
```
➜ maketest test_docker.py::test_multiple_tags --logs -x
```

fix: _REPO_TAGS missing all pushed tags

---

.github/workflows/tests.yml

It was not possible to trigger new test run in CI

ci: allowing to trigger tests adhoc

---

CHANGELOG.md
src/docker/dockerfile.nim
src/util.nim
tests/functional/test_docker.py

`DOCKER_COPY_IAMGES` has incorrect base image
It was not parsing whenever `--from` provided a stage index, not its alias. In docker you can pass either:
```dockerfile
FROM alpine AS one
FROM alpine AS two
COPY --from=one /foo /bar
COPY --from=0 /foo /bar
```
```
➜ maketest test_docker.py::test_base_images --pdb --logs
```

fix: incorrect DOCKER_COPY_IMAGES for COPY --from=<index>

---

src/util.nim

macos build cant compile with this typo

fix: macos compilation

---

CHANGELOG.md
src/chalk_common.nim
src/docker/cmdline.nim
src/docker/dockerfile.nim
src/docker/exe.nim
src/semver.nim
tests/functional/data/dockerfiles/valid/sample_3/Dockerfile
tests/unit/test_semver.nim

Builds which specify frontend can sometimes fallback due to incompatible `--build-arg`
Not all older frontends support `--build-arg` and sometimes they do no specify the version as part of the syntax directive. For example:
```
```
Chalk cannot infer anything about the meaning of `experimental` as its not pinned to any version. Therefore we call the dockerfile frontend container and check its actual version.
This is possibly not as efficient even if the version is specified however that would also require some heuristics. For example:
```
```
As `1` can change over time it might not be clear which syntax should actually be honored. Therefore it is probably a lot simpler to simply ask it what version it is instead of possibly error-prone version detection heuristics.
```
➜ maketest …
```

fix: check buildkit frontend version to determine context arg compatibility

---

CHANGELOG.md
src/commands/cmd_exec.nim

heartbeats have incorrect timestamp
Heartbeat reports had older timestamps. Reporting state was cleared before sleeping for the heartbeat which meant that timestamp was always off by the heartbeats interval - default 10 minutes.
Run 
```
./chalk exec -- sleep 300
```
and observe reported timestamp locally.

fix: heartbeats timestamp

---

CHANGELOG.md
src/configs/base_keyspecs.c4m
src/configs/base_report_templates.c4m
src/configs/crashoverride.c4m
src/plugins/externalTool.nim
src/util.nim
tests/functional/data/configs/composable/valid/sast/enable_sast.c4m
tests/functional/test_plugins.py

To help analyze whats the overhead of the tool, report its duration as a separate key
```
➜ maketest test_plugins.py::test_semgrep --pdb
```

feat: adding EXTERNAL_TOOL_DURATION key

---

CHANGELOG.md
configs/co/secret_scanner.c4m
src/chalk_common.nim
src/con4mfuncs.nim
src/configs/base_keyspecs.c4m
src/configs/base_report_templates.c4m
src/configs/chalk.c42spec
src/configs/crashoverride.c4m
src/configs/sastconfig.c4m
src/configs/sbomconfig.c4m
src/configs/secretscannerconfig.c4m
src/confload.nim
src/normalize.nim
src/plugins/externalTool.nim
src/selfextract.nim
tests/functional/conf.py
tests/functional/data/configs/composable/valid/secret_scanner/enable_secrets.c4m
tests/functional/test_plugins.py
tests/functional/test_sink.py

Chalk supports limited number of external tools it can natively run:
* syft
* semgrep
Secret scanning is a common tool people might want to run so this PR adds support for running secret scanner via `trufflehog` - https://github.com/trufflesecurity/trufflehog
Note that `trufflehog` actively validates secrets which currently cannot be reliably disabled. See https://github.com/trufflesecurity/trufflehog/issues/1748 https://github.com/trufflesecurity/trufflehog/issues/2620. As a result if it finds for example AWS keys, it will actively check if they are active by making API calls to AWS. This is good to reduce noise however this active scanning might not be desirable in some places so enabling it should be done with that caveat in mind.
Note that valid AWS creds must be provided to run …

feat: trufflehog external tool

---

src/autocomplete/default.bash
src/autocomplete/mac.bash

Adds the _chalk_docker_autocompletions function to autocomplete docker commands
#281 
Small one line change to add autocompletions for docker commands 
source autocompletion file, and run `chalk docker <tab><tab>` and `chalk docker rmi <tab><tab>` to confirm whether tab completion is working for docker and docker subcommands

bug: chalk docker autocomplete

---

src/configs/chalk.c42spec

this was used in older con4m autogenerate script which is no more so these are moot now

refactor: remove obsolete gen_* spec fields

---

CHANGELOG.md
configs/co/object_store.c4m
src/attestation/get.nim
src/auth.nim
src/chalk_common.nim
src/chalkjson.nim
src/con4mfuncs.nim
src/configs/base_callbacks.c4m
src/configs/base_keyspecs.c4m
src/configs/chalk.c42spec
src/configs/sastconfig.c4m
src/configs/sbomconfig.c4m
src/configs/secretscannerconfig.c4m
src/normalize.nim
src/object_store/api.nim
src/object_store/presign.nim
src/plugins/codecElf.nim
src/plugins/codecFallbackElf.nim
src/plugins/codecMacOs.nim
src/plugins/codecPythonPyc.nim
src/plugins/codecZip.nim
src/reporting.nim
src/run_management.nim
src/sinks.nim
tests/functional/data/configs/composable/valid/sboms/enable_sboms.c4m
tests/functional/poetry.lock
tests/functional/pyproject.toml
tests/functional/server/chalk.py
tests/functional/test_plugins.py
tests/functional/testing.c4m

Chalk reports can be very large which send duplicate data across builds (e.g. sbom).
Instead of reporting raw value in the report template, each key could be uploaded to an object store and its reference be included in the report. This allows to deduplicate large keys independently to object store and then refer the same object across reports.
To use it object store needs to be configured:
```
object_store_config foo {
object_store: "presign"
object_store_presign {
uri: "http://localhost:8080/v0.1/objects"
}
}
```
Then per report template the object store can be used for specific keys:
```
report_template foo {
key.SBOM.object_store = "foo"
}
```
Currently only `presign` object store is implemented however the infrastructure is ready to add more object stores in the future such as `s3`, …

feat: object store per key in reports

---

src/configs/crashoverride.c4m

Sometimes when exec is processed before build, build datetime is not known yet
The key was already part of the mark template:
https://github.com/crashappsec/chalk/blob/962a9b6698f2107234058746b6284a9027faec88/src/configs/base_chalk_templates.c4m#L263-L264
We just werent posting it in the report template.

feat: report chalkmark chalked date on exec

---

CHANGELOG.md
src/configs/chalk.c42spec
src/plugins/procfs.nim
tests/functional/data/configs/netstats.c4m
tests/functional/test_plugins.py

we would like to send subset of tcp sockets in heartbeats
this allows to filter TCP sockets with what statuses are reported in _OP_TCP_SOCKET_INFO as in most cases WAIT sockets are not super interesting...
```
➜ maketest test_plugins.py::test_network --pdb
```

feat: network.tcp_socket_statuses config

---

CHANGELOG.md
src/attestation_api.nim
src/configs/base_keyspecs.c4m

cosign payload is not included in the chalk report making it impossible to validate the cosign signatures externally
This changes shape of `_SIGNATURES` to be the full cosign attestation object vs just the signatures.
sign any image locally and check `_SIGNATURES`

feat: include full attestation payload in cosign _SIGNATURE

---

CHANGELOG.md
SECURITY.md
src/configs/base_chalk_templates.c4m
src/configs/base_keyspecs.c4m
src/configs/base_plugins.c4m
src/configs/base_report_templates.c4m
src/configs/crashoverride.c4m
src/plugins/vctlGit.nim
tests/functional/test_git.py

this can allow to catch cases when the build is done on a mutated repo which is missing files tracked by git
SBOM does not find any deps during a build even though a repo has `requirements.txt`.
This key reports all files already tracked in git but are missing on disk during a build which can help to troubleshoot cases where the build does not match a state of git.
```
➜ maketest test_git.py::test_repo
```

feat: VCS_MISSING_FILES key

---

src/plugins/elf.nim

- Added error case for when adding a chalk mark would increment the section count up to where it should be moved out of the  ELF e_shnum field and into the first section table entry (if incrementing e_shnum would hit SHN_LORESERVE). This is  rare so we shouldn't need to support it, adding support now feels unnecessary, but at least we will detect that we don't support it.
- Added error case check for e_phnum being PX_XNUM, meaning that the real count of segments has been moved into the first shtab entry. Much like the section count check mentioned above, this case is rare and we likely won't need to support it, but without adding this check we would possibly not account for segments in our range calculation and thus not accurately see if ELF modification (inserting the chalk mark) would …

Fix to properly error out on very rare but unsupported ELF corner cases with PHTAB and SHTAB

---

CHANGELOG.md
SECURITY.md
chalk.nimble
src/chalkjson.nim
src/configs/base_keyspecs.c4m
src/normalize.nim
src/object_store/api.nim
src/util.nim
tests/functional/chalk/runner.py
tests/functional/test_docker.py

In CI:
```
docker build ..
docker push ..
```
`docker push` will report incorrect `METADATA_ID` as its computation will have incorrect `BUILD_CONTACT` key as its key in the collected data will be merged twice hence have duplicate entries
Resolving it by both:
* better `.merge` implementation doesnt duplicate array items
* whenever chalkmark is already cached (for already chalked artifacts), its used as-is for chalkmark `ChalkDict` computation instead of again collecting only the keys in the chalk template.
```
➜ maketest test_docker.py::test_build_and_push[valid/empty-10.10.20.30:5044-False-True-False]
```

fix: METADATA_ID in docker push

---

src/utils/ip.nim
tests/unit/test_ip.nim

ip cidr matching wasnt working correctly for ipv6 with `/64`
Will allow to filter ips if they are special purpose
```
➜ make unit-tests args="pattern tests/unit/test_ip.nim"
```

refactor: add ip.isSpecialPurpose()

---

CHANGELOG.md
src/docker/ids.nim
tests/unit/test_docker_ids.nim

Referencing ipv6 docker image incorrected parsed some parts of the name
Docker supports ipv6 image names which chalk wasnt supporting
```
➜ make unit-tests args="pattern tests/unit/test_docker_ids.nim"
```

fix: support ipv6 docker registry names

---

CHANGELOG.md
chalk.nimble
src/configs/base_init.c4m
src/configs/chalk.c42spec
src/plugins/codecCerts.nim
src/sinks.nim
src/subscan.nim

Certs subscan adds a lot of overhead to builds
allows to blacklist/whitelist files for cert checks
also bumps con4m to bring much more efficient FS walk from nimutils
n/a

feat: certs filtering behavior configs

---

chalk.nimble

sometimes this error would pop up:
```
error: object store: failed to canonicalize SAST due to: docker: [embedded config]: 64:39: 
Unhandled error when running builtin call: canonicalize_toolerror is: options.nim(137, 5) `not val.isNil` 
canonicalized := canonicalize_tool(name, value)
^
```
it didnt break anything actively, just was not canonicalizing correctly for the object store hash
n/a

fix: bump con4m to fix get(dict[k, v]) builtin

---

configs/co/build_observables.c4m
configs/co/build_observables_key.c4m

also looks like `command_name()` check wasnt being honored in the template config as the key was subbed during exec so moving check to the callback

fix: remove jq build observe dependency

---

CHANGELOG.md
src/plugins/ciCodeBuild.nim
src/plugins/ciGithub.nim
src/plugins/ciGitlab.nim
tests/functional/test_plugins.py

`BUILD_TRIGGER` shows up as `other:pull_request` in github builds
no real benefit normalizing the value if the triggers are added over time
```
maketest test_plugins.py::test_github
```

fix: dont normalize BUILD_TRIGGER

---

CHANGELOG.md
src/configs/secretscannerconfig.c4m
tests/functional/test_plugins.py

trufflehog report includes actual secret values which are reported by chalk
drop raw secrets from trufflehog reports but report the raw secret hash for allowing to dedup secrets on the backend
```
➜ aws_creds maketest test_plugins.py::test_trufflehog[True] --logs --pdb
```

feat: remove raw secrets from trufflehog report

---

CHANGELOG.md
chalk.nimble
src/chalk.nim
src/con4mfuncs.nim
src/configs/ioconfig.c4m

even when setting `color: false`, logs still contained color ansi codes for the log level prefixes like `error:`. 
fixes https://github.com/crashappsec/chalk/issues/297
underlying issue was in nimutils https://github.com/crashappsec/nimutils/pull/92
```
✗ docker run  --rm -v ./chalk:/chalk alpine /chalk --log-level=trace version
```
ensure colors do not appear without `-t` flag to docker

fix: honor color setting in logs

---

CHANGELOG.md
SECURITY.md
src/configs/base_keyspecs.c4m
src/util.nim

Chalk makes some builds slower which utilize all CPU cores.
Use default switchboard timeout of 1 sec.
Run some docker builds which have go build in them

fix: chalk pegging CPU while IO polling for subprocs

---

.dockerignore
CHANGELOG.md
Makefile
chalk.nimble
configs/co/heartbeat2.c4m
configs/use_heartbeats.c4m
src/commands/cmd_exec.nim
src/commands/cmd_version.nim
src/configs/base_init.c4m
src/configs/base_keyspecs.c4m
src/configs/chalk.c42spec
src/configs/getopts.c4m
src/docker/extract.nim
src/plugin_api.nim
src/plugins/codecElf.nim
src/plugins/elf.nim
src/plugins/system.nim
src/reporting.nim
src/run_management.nim
src/selfextract.nim
src/types.nim
src/utils/exe.nim
src/utils/file_string_stream.nim
src/utils/files.nim
src/utils/strings.nim
tests/functional/data/configs/composable/valid/multiple/sample_2.c4m
tests/functional/data/configs/docker_heartbeat.c4m
tests/functional/data/configs/heartbeat.c4m
tests/unit/test_file_string_stream.nim

heartbeats/postexec is taking too much memory (>300Mb).
allow to read elfs only sections we actually need vs reading/parsing the whole file. This brights up regular elf parsing memory utilization to around 60M so for postexec/heartbeats its around 100M locally now
```
V reset;
echo > ~/.local/chalk/chalk.log;
docker rm mem;
docker run -it \
--name mem \
-v $PWD:$PWD \
-w $PWD \
-v (echo '
exec.postexec.run = true
exec.heartbeat = true
' | psub):/etc/chalk.c4m \
-v $HOME/.local/chalk:/root/.local/chalk \
-v ./chalk.json:/chalk.json \
-v (echo '
/etc/ssl/certs/ca-certificates.crt
' | psub):/tmp/prep_postexec.txt \
--entrypoint=$PWD/chalk \
alpine \
--trace exec --chalk-as-parent -- \
/bin/sh -c '
tail /etc/ssl/certs/ca-certificates.crt
sleep 20
'
```
and then in another tab:
```
✗ while …
```

fix: smaller elf parsing memory utilization

---

src/commands/cmd_exec.nim
src/types.nim

small nit PR
otherwise `_OP_ARTIFACT_ACCESSED` is being always sent as `false` for all other reports

fix: only set artifact accessed in postexec

---

CHANGELOG.md
chalk.nimble
src/sinks.nim

in deployed environments, chalk logs are not easily searchable or ignorable as they are not structured logs
switch to json structured logging for non-interactive shell sessions
```
➜ docker run --rm -v ./chalk:/chalk alpine /chalk version
```
will show json logs

feat: switch to json logs when non-interactive and no color

---

CHANGELOG.md
src/utils/terminal.nim

running `./setup.sh` would hang on `chalk version` when running in an interactive shell
otherwise there are cases when chalk hangs on exit when chalk receices SIGTTOU while resetting terminal state
in interactive shell
```
➜ sh ./setup.sh --token=$CHALK_TOKEN   --saas   --chalk-path=./chalk   --no-wrap  --timeout=30 --copy-from=../chalk/chalk --debug
```

fix: handle SIGTTOU and SIGTTIN

---

src/con4mfuncs.nim
src/plugins/conffile.nim
src/run_management.nim
src/selfextract.nim
src/types.nim

during chalk load which is registering additional keys would see:
```
error: When collecting chalk-time host info, plugin implementation conffile threw an exception it didn't handle: get() of an attribute that isn't set.
error: When collecting chalk-time artifact data, plugin implementation conffile threw an exception it didn't handle (artifact = /home/root/Code/co/setup-chalk-action/chalk): get() of an attribute that isn't set.
error: When collecting run-time host info, plugin implementation conffile threw an exception it didn't handle: get() of an attribute that isn't set.
```
while testing the configuration some keys are partially registered which shows non-errors as error logs while calculating the report while doing the command report
for the log updates:
```
➜ ./chalk load …
```

fix: handle confspec errors during chalk load

---

CHANGELOG.md
src/config.nim
src/configs/chalk.c42spec
src/plugins/codecZip.nim
src/types.nim
tests/functional/data/configs/serverless_zip.c4m

there are scenarios when injecting chalk binary into zip will make it too large (e.g. lambda zip deployment) in which case chalk should bail out injecting chalk binary
add option to bypass binary injection when zip is >= threashold
```
➜ dd if=/dev/urandom bs=1M count=50 > chalk.random
➜ zip chalk.zip chalk.random
➜ ./chalk insert chalk.zip --inject-binary-into-zip
```
dont think this small case needs explicit integration test so prolly ok for now as-is (zip codec is very slow too)

feat: add zip inject binary threshold

---

CHANGELOG.md
src/con4mfuncs.nim
src/config.nim
src/types.nim
tests/functional/chalk/runner.py
tests/functional/data/configs/copy_report_template_keys.c4m
tests/functional/test_command.py

for custom keys defined along with co chalk profile loaded, there are error logs which can alert in monitoring stack
if the copy is not lazy, then depending on the order of loaded modules, some keys might not be copied into the destination report template
for example:
```
copy_report_template_keys("source", "destination")
keyspec X_TEST {
kind:  ChalkTimeHost
type:  string
value: ""
}
report_template.source.key.X_TEST.use = true
```
in above example `one.c4m` copies `source` into `destination` report template. At a later time if another key is added to `source` report template, it wont be copied to the `destination` report template as at the time of the time that key is not fully defined.
By making the copy lazy, all keys are copied when report template is referenced in chalk hence all …

fix: lazy copy_report_template_keys()

---

CHANGELOG.md
src/attestation/utils.nim

`chalk setup` would not download cosign
manual testing with `setup.sh` which would be installing cosign

fix: cosign downloading
