crashappsec/chalk

README.md

fix(README): fix typo in CLA link

---

src/plugins/elf.nim

This should enable support for AARCH64

Removed the check which only allowed AMD64

---

README.md

Closes #35 
Fix grammatical error.
n/a

[style] Readme tweak

---

docker-bake.hcl

build(bake): pushing cache in docker-bake to update cache in CI

---

SECURITY.md

Issue #840 
Add in a minimal `security,md` to provide an easy references for currently supported versions as well as how to report a security problem.
This is a repo meta-documentation only change only, no testing required

docs(security.md): create basic security.md

---

src/configs/base_keyspecs.c4m
src/configs/base_report_templates.c4m
src/configs/chalk.c42spec
src/configs/getopts.c4m

None
Fixing up multi-merge regression
Chalk should now compile !

fix(chalk): fix up multi-merge

---

.pre-commit-config.yaml
chalk.nimble
src/commands/cmd_dump.nim
src/commands/cmd_help.nim
src/commands/cmd_load.nim
src/commands/cmd_version.nim
src/con4mfuncs.nim
src/configs/base_keyspecs.c4m
src/configs/base_plugins.c4m
src/docs/core-release-notes.md
src/normalize.nim
src/selfextract.nim
src/sinks.nim
tests/test_docker.py

Release should have been 0.2.0; fixed a few bugs and added some tests.

release(0.2.0)

---

chalk.nimble
src/configs/base_keyspecs.c4m

Closes #75 
It used to be that the value set by the attribute couldn't be used in the component, without some definition in the component (that the attribute overrides).  I removed that restriction and it somehow fixes it??
I probably will remove the same restriction for variables soon.
If tests pass and the howto for application inventory works...

fix(con4m): Address issue where attribute parameter value wasn't being always being picked up 

---

server/server/api.py

this fixes the sink using put method to send reports to server
see swagger at the server endpoint `/docs`

accepting both POST/PUT for the report endpoint

---

chalk.nimble
src/configs/base_keyspecs.c4m

bumping version to 0.2.2

---

chalk.nimble
config.nims
src/attestation.nim
src/chalk.nim
src/commands/cmd_dump.nim
src/commands/cmd_help.nim
src/commands/cmd_version.nim
src/con4mfuncs.nim
src/configs/chalk.c42spec
src/configs/getopts.c4m
src/configs/ioconfig.c4m
src/reportcache.nim
src/sinks.nim
src/util.nim
tests/chalk/runner.py
tests/test_command.py

As I'm working towards some major under-the-hood con4m improvements, I need to keep Chalk aligned with downstream development to avoid more pain later.
Lots of little changes to adapt to nimutils changes made while workin…g on con4m stuff. file locking now uses flock() and the use of tables / formatting is much simplified. Also am using a less obnoxious default style.
Instead of having to generate HTML for tables, lists, etc, there's now a much more sane API... most HTML tags get their own functions (but not for 1 letter tags; `paragraph()` instead of `p()`, which had some weird conflict). `quickTable()` is a wrapper around `table(), tr(), td(),` etc.
Current testing should be sufficient.

refactor(nimutils): Adjust to api changes

---

SECURITY.md

Supported version in `SECURITY.md` was out of date
Bumped the version to current `0.2.2`release
Read the `SECURITY.md` file with your eyeballs and ensure version `0.2.2` is present 👍

fix(SECURITY.md): bump supported version to 0.2.2

---

src/configs/base_keyspecs.c4m

Appropriate min version for the upcoming release

fix: bump version for techstacks

---

SECURITY.md

No linked issue
Bump version specified as supported in `SECURITY.md` to `0.3.0`
No tests required

docs(security.md): bump supportted version to 0.3.0

---

chalk.nimble
src/configs/base_keyspecs.c4m
src/docs/core-release-notes.md

this way main is no longer on 0.3.0

bumping version for the next release

---

.clabot

None
Link was broken, now its not
Click the link

fix(clabot): broken link

---

.pre-commit-config.yaml
CHANGELOG.md
src/configs/base_keyspecs.c4m

we have a few PRs coming in. this will allow to update changelog in each PR easily

docs: bumping version for next section of CHANGELOG

---

CHANGELOG.md
src/configs/base_keyspecs.c4m

prepping bump for after the release

build: bumping version to 0.3.4-dev for next release

---

CHANGELOG.md
chalk.nimble

fixes https://github.com/crashappsec/chalk/issues/125
see issue ^^
manually attempt to load a component with a default param

fix: load honors default param during load prompt

---

CHANGELOG.md

changelog does not match github releases format
this matches the format we use in the github releases and is slightly prettier to read :D

docs: adding parens around PR links in changelog

---

CHANGELOG.md

docs: fixing changelog headers

---

src/plugins/cloudMetadata.nim

sometimes metadata response with non-200 status code and we are not sure why. this should help debugging that

feat: logging response status + body on cloud metadata errors

---

src/plugins/awsLambda.nim
src/plugins/codecMacOs.nim
src/plugins/codecSource.nim
src/plugins/ownerAuthors.nim
src/plugins/procfs.nim
src/plugins/vctlGit.nim

error logs dont show full cause why something failed
this will help debugging plugin errors from chalk reports

fix: logging exception msg in plugin exceptions

---

src/docker/extract.nim

previously we were trying:
* `docker run --entrypoint=cat <image> /chalk.json`
* `docker save <image> && unzip ...`
This was pretty fast for images which had `cat` available however it was much slower for distroless images. For example chalks own image `crashappsec/chalk` was pretty slow to extract as its distroless. In addition `cat` only worked if docker was able to execute `cat` with platform compatibility.
Right now we simply create a container but we never start it. It then allows to extract a file from the container via `docker cp` without too much fuss similarly how we were extracting it before. As the container is never started its version compatibility is irrelevant as nothing actually runs. Then we simply remove container. Simple and fast.
```
➜ make tests …
```

refactor: much faster docker image extract

---

configs/co/attestation_easy.c4m
configs/co/crashoverride.c4m
configs/co/docker.c4m
configs/co/env_vars.c4m
configs/co/profile.c4m
configs/co/sast.c4m
configs/co/sbom.c4m

these will be pulled by dynamic generated component

feat: adding co/ configs for custom chalk profiles

---

README.md

docs(readme) adds additional links for context, header formatting

---

src/chalk_common.nim
src/docker/build.nim
src/docker/collect.nim
src/docker/dockerfile.nim
src/docker/git.nim
src/docker/scan.nim
src/plugins/system.nim
tests/functional/chalk/runner.py
tests/functional/setup.cfg
tests/functional/test_docker.py
tests/functional/testing.c4m
tests/functional/utils/dict.py
tests/functional/utils/docker.py

In addition to reporting the base image of the target section, all other base images are also collected and reported in _COLLECTED_ARTIFACTS.
```
➜ reset; make tests args="test_docker.py::test_base_images --logs --pdb"
```

feat: reporting all base images in _COLLECTED_ARTIFACTS

---

src/docker/exe.nim
src/docker/ids.nim
src/docker/json.nim
src/docker/manifest.nim
src/docker/registry.nim
src/plugins/externalTool.nim

as bunch of previous PRs were stacked, could not easily address them so getting back to them here

refactor: addressing previous PR comments

---

CHANGELOG.md
SECURITY.md
src/configs/base_keyspecs.c4m

build: 0.5.0 release

---

CHANGELOG.md
src/configs/base_chalk_templates.c4m
src/configs/base_keyspecs.c4m
src/configs/base_plugins.c4m
src/configs/base_report_templates.c4m
src/configs/crashoverride.c4m
src/plugin_load.nim
src/plugins/ciCodeBuild.nim
src/plugins/ciGithub.nim
src/plugins/ciGitlab.nim
tests/functional/test_plugins.py

chalk does not send any metadata about code build pipelines
very basic for now but we should be able to collect some information
```
➜ maketest test_plugins.py::test_codebuild_git test_plugins.py::test_codebuild_s3 test_plugins.py::test_gitlab test_plugins.py::test_github --pdb
```

feat: add AWS codebuild plugin

---

README.md

docs(readme): Update links to new docs location

---

configs/co/heartbeat_netstats.c4m

this is for the CO integration

feat: add netstats module for heartbeats

---

CHANGELOG.md
src/plugins/cloudMetadata.nim

Its hard to find IMDS errors in logs.
Will allow to flag these errors better in the UI
N/A

feat: report all imds errors as failed keys

---

CHANGELOG.md
src/configs/base_keyspecs.c4m
src/configs/base_plugins.c4m
src/configs/base_report_templates.c4m
src/configs/crashoverride.c4m
src/plugins/codecCerts.nim
src/utils/certs.c
tests/functional/data/configs/certs.c4m
tests/functional/test_cert.py

Sometimes its useful to show the signature which chalk doesnt collect
Collect cert signature
```
➜ maketest test_cert.py --logs
```

feat: X509_SIGNATURE key

---

src/configs/base_chalk_templates.c4m

forgot to include it in last pr

feat: add BUILD_UNIQUE_ID to chalkmark

---

.editorconfig
.github/workflows/dust-tests.yml
.github/workflows/tests.yml
.github/workflows/unit-tests.yml
.pre-commit-config.yaml
Makefile
dust-lambda-extension/.editorconfig
dust-lambda-extension/.gitignore
dust-lambda-extension/Makefile
dust-lambda-extension/README.md
dust-lambda-extension/extensions/dust
tests/functional/server/app.py

Setting up dust sub-project as we approach our initial release. Release automation and docs to follow.

feat(dust): dust extension repo setup
